use marista
go

delete from Country where CountryId!='bg'

insert into Country (CountryId, CountryName, CountryTypeId)
values
('AD', 'Andorra', '4'),
('AE', 'United Arab Emirates', '4'),
('AF', 'Afghanistan', '4'),
('AG', 'Antigua and Barbuda', '4'),
('AI', 'Anguilla', '4'),
('AL', 'Albania', '3'),
('AM', 'Armenia', '4'),
('AN', 'Netherlands Antilles', '4'),
('AO', 'Angola', '4'),
('AQ', 'Antarctica', '4'),
('AR', 'Argentina', '4'),
('AS', 'American Samoa', '4'),
('AT', 'Austria', '3'),
('AU', 'Australia', '4'),
('AW', 'Aruba', '4'),
('AZ', 'Azerbaijan', '4'),
('BA', 'Bosnia and Herzegovina', '3'),
('BB', 'Barbados', '4'),
('BD', 'Bangladesh', '4'),
('BE', 'Belgium', '3'),
('BF', 'Burkina Faso', '4'),
('BH', 'Bahrain', '4'),
('BI', 'Burundi', '4'),
('BJ', 'Benin', '4'),
('BM', 'Bermuda', '4'),
('BN', 'Brunei', '4'),
('BO', 'Bolivia', '4'),
('BR', 'Brazil', '4'),
('BS', 'Bahamas', '4'),
('BT', 'Bhutan', '4'),
('BV', 'Bouvet Island', '4'),
('BW', 'Botswana', '4'),
('BY', 'Belarus', '3'),
('BZ', 'Belize', '4'),
('CA', 'Canada', '4'),
('CC', 'Cocos [Keeling] Islands', '4'),
('CD', 'Congo [DRC]', '4'),
('CF', 'Central African Republic', '4'),
('CG', 'Congo [Republic]', '4'),
('CH', 'Switzerland', '3'),
('CI', 'Côte d''Ivoire', '4'),
('CK', 'Cook Islands', '4'),
('CL', 'Chile', '4'),
('CM', 'Cameroon', '4'),
('CN', 'China', '4'),
('CO', 'Colombia', '4'),
('CR', 'Costa Rica', '4'),
('CU', 'Cuba', '4'),
('CV', 'Cape Verde', '4'),
('CX', 'Christmas Island', '4'),
('CY', 'Cyprus', '3'),
('CZ', 'Czech Republic', '3'),
('DE', 'Germany', '3'),
('DJ', 'Djibouti', '4'),
('DK', 'Denmark', '3'),
('DM', 'Dominica', '4'),
('DO', 'Dominican Republic', '4'),
('DZ', 'Algeria', '4'),
('EC', 'Ecuador', '4'),
('EE', 'Estonia', '3'),
('EG', 'Egypt', '4'),
('EH', 'Western Sahara', '4'),
('ER', 'Eritrea', '4'),
('ES', 'Spain', '3'),
('ET', 'Ethiopia', '4'),
('FI', 'Finland', '3'),
('FJ', 'Fiji', '4'),
('FK', 'Falkland Islands [Islas Malvinas]', '4'),
('FM', 'Micronesia', '4'),
('FO', 'Faroe Islands', '3'),
('FR', 'France', '3'),
('GA', 'Gabon', '4'),
('GB', 'United Kingdom', '3'),
('GD', 'Grenada', '4'),
('GE', 'Georgia', '4'),
('GF', 'French Guiana', '4'),
('GG', 'Guernsey', '4'),
('GH', 'Ghana', '4'),
('GI', 'Gibraltar', '4'),
('GL', 'Greenland', '4'),
('GM', 'Gambia', '4'),
('GN', 'Guinea', '4'),
('GP', 'Guadeloupe', '4'),
('GQ', 'Equatorial Guinea', '4'),
('GR', 'Greece', '2'),
('GS', 'South Georgia and the South Sandwich Islands', '4'),
('GT', 'Guatemala', '4'),
('GU', 'Guam', '4'),
('GW', 'Guinea-Bissau', '4'),
('GY', 'Guyana', '4'),
('GZ', 'Gaza Strip', '4'),
('HK', 'Hong Kong', '4'),
('HM', 'Heard Island and McDonald Islands', '4'),
('HN', 'Honduras', '4'),
('HR', 'Croatia', '3'),
('HT', 'Haiti', '4'),
('HU', 'Hungary', '3'),
('ID', 'Indonesia', '4'),
('IE', 'Ireland', '3'),
('IL', 'Israel', '4'),
('IM', 'Isle of Man', '4'),
('IN', 'India', '4'),
('IO', 'British Indian Ocean Territory', '4'),
('IQ', 'Iraq', '4'),
('IR', 'Iran', '4'),
('IS', 'Iceland', '3'),
('IT', 'Italy', '3'),
('JE', 'Jersey', '4'),
('JM', 'Jamaica', '4'),
('JO', 'Jordan', '4'),
('JP', 'Japan', '4'),
('KE', 'Kenya', '4'),
('KG', 'Kyrgyzstan', '4'),
('KH', 'Cambodia', '4'),
('KI', 'Kiribati', '4'),
('KM', 'Comoros', '4'),
('KN', 'Saint Kitts and Nevis', '4'),
('KP', 'North Korea', '4'),
('KR', 'South Korea', '4'),
('KW', 'Kuwait', '4'),
('KY', 'Cayman Islands', '4'),
('KZ', 'Kazakhstan', '4'),
('LA', 'Laos', '4'),
('LB', 'Lebanon', '4'),
('LC', 'Saint Lucia', '4'),
('LI', 'Liechtenstein', '4'),
('LK', 'Sri Lanka', '4'),
('LR', 'Liberia', '4'),
('LS', 'Lesotho', '4'),
('LT', 'Lithuania', '3'),
('LU', 'Luxembourg', '3'),
('LV', 'Latvia', '3'),
('LY', 'Libya', '4'),
('MA', 'Morocco', '4'),
('MC', 'Monaco', '4'),
('MD', 'Moldova', '3'),
('ME', 'Montenegro', '3'),
('MG', 'Madagascar', '4'),
('MH', 'Marshall Islands', '4'),
('MK', 'Macedonia [FYROM]', '2'),
('ML', 'Mali', '4'),
('MM', 'Myanmar [Burma]', '4'),
('MN', 'Mongolia', '4'),
('MO', 'Macau', '4'),
('MP', 'Northern Mariana Islands', '4'),
('MQ', 'Martinique', '4'),
('MR', 'Mauritania', '4'),
('MS', 'Montserrat', '4'),
('MT', 'Malta', '3'),
('MU', 'Mauritius', '4'),
('MV', 'Maldives', '4'),
('MW', 'Malawi', '4'),
('MX', 'Mexico', '4'),
('MY', 'Malaysia', '4'),
('MZ', 'Mozambique', '4'),
('NA', 'Namibia', '4'),
('NC', 'New Caledonia', '4'),
('NE', 'Niger', '4'),
('NF', 'Norfolk Island', '4'),
('NG', 'Nigeria', '4'),
('NI', 'Nicaragua', '4'),
('NL', 'Netherlands', '3'),
('NO', 'Norway', '3'),
('NP', 'Nepal', '4'),
('NR', 'Nauru', '4'),
('NU', 'Niue', '4'),
('NZ', 'New Zealand', '4'),
('OM', 'Oman', '4'),
('PA', 'Panama', '4'),
('PE', 'Peru', '4'),
('PF', 'French Polynesia', '4'),
('PG', 'Papua New Guinea', '4'),
('PH', 'Philippines', '4'),
('PK', 'Pakistan', '4'),
('PL', 'Poland', '3'),
('PM', 'Saint Pierre and Miquelon', '4'),
('PN', 'Pitcairn Islands', '4'),
('PR', 'Puerto Rico', '4'),
('PS', 'Palestinian Territories', '4'),
('PT', 'Portugal', '3'),
('PW', 'Palau', '4'),
('PY', 'Paraguay', '4'),
('QA', 'Qatar', '4'),
('RE', 'Réunion', '4'),
('RO', 'Romania', '2'),
('RS', 'Serbia', '2'),
('RU', 'Russia', '3'),
('RW', 'Rwanda', '4'),
('SA', 'Saudi Arabia', '4'),
('SB', 'Solomon Islands', '4'),
('SC', 'Seychelles', '4'),
('SD', 'Sudan', '4'),
('SE', 'Sweden', '3'),
('SG', 'Singapore', '4'),
('SH', 'Saint Helena', '4'),
('SI', 'Slovenia', '3'),
('SJ', 'Svalbard and Jan Mayen', '4'),
('SK', 'Slovakia', '3'),
('SL', 'Sierra Leone', '4'),
('SM', 'San Marino', '4'),
('SN', 'Senegal', '4'),
('SO', 'Somalia', '4'),
('SR', 'Suriname', '4'),
('ST', 'São Tomé and Príncipe', '4'),
('SV', 'El Salvador', '4'),
('SY', 'Syria', '4'),
('SZ', 'Swaziland', '4'),
('TC', 'Turks and Caicos Islands', '4'),
('TD', 'Chad', '4'),
('TF', 'French Southern Territories', '4'),
('TG', 'Togo', '4'),
('TH', 'Thailand', '4'),
('TJ', 'Tajikistan', '4'),
('TK', 'Tokelau', '4'),
('TL', 'Timor-Leste', '4'),
('TM', 'Turkmenistan', '4'),
('TN', 'Tunisia', '4'),
('TO', 'Tonga', '4'),
('TR', 'Turkey', '2'),
('TT', 'Trinidad and Tobago', '4'),
('TV', 'Tuvalu', '4'),
('TW', 'Taiwan', '4'),
('TZ', 'Tanzania', '4'),
('UA', 'Ukraine', '3'),
('UG', 'Uganda', '4'),
('UM', 'U.S. Minor Outlying Islands', '4'),
('US', 'United States', '4'),
('UY', 'Uruguay', '4'),
('UZ', 'Uzbekistan', '4'),
('VA', 'Vatican City', '3'),
('VC', 'Saint Vincent and the Grenadines', '4'),
('VE', 'Venezuela', '4'),
('VG', 'British Virgin Islands', '4'),
('VI', 'U.S. Virgin Islands', '4'),
('VN', 'Vietnam', '4'),
('VU', 'Vanuatu', '4'),
('WF', 'Wallis and Futuna', '4'),
('WS', 'Samoa', '4'),
('XK', 'Kosovo', '3'),
('YE', 'Yemen', '4'),
('YT', 'Mayotte', '4'),
('ZA', 'South Africa', '4'),
('ZM', 'Zambia', '4'),
('ZW', 'Zimbabwe', '4')

delete from CountryDelivery


insert into countrydelivery(FromWeight, ToWeight, Price,CountryTypeId)
values

(0,	20,	0.79, 1), 
(21, 50, 0.79, 1), 
(51, 100, 0.79, 1), 
(101, 150, 0.89, 1), 
(151, 250, 0.89, 1), 
(251, 350, 1.02, 1), 
(351, 500, 1.02, 1), 
(501, 1000, 1.15, 1), 
(1001, 2000, 1.25, 1),
(0, 20, 2.81, 2),
(21, 50, 2.97, 2),
(51, 100, 3.32, 2),
(101, 150, 3.73, 2),
(151, 250, 4.60, 2),
(251, 350, 5.11, 2),
(351, 500, 6.29, 2),
(501, 1000, 9.71, 2),
(1001, 2000, 13.55, 2),
(0, 20, 2.97, 3),
(21, 50, 3.22, 3),
(51, 100, 3.73, 3),
(101, 150, 4.19, 3),
(151, 250, 5.06, 3),
(251, 350, 5.88, 3),
(351, 500, 7.06, 3),
(501, 1000, 11.66, 3),
(1001, 2000, 16.62, 3),
(0, 20, 3.32, 4),
(21, 50, 3.89, 4),
(51, 100, 4.35, 4),
(101, 150, 5.11, 4),
(151, 250, 6.65, 4),
(251, 350, 7.77, 4),
(351, 500, 9.71, 4),
(501, 1000, 14.32, 4),
(1001, 2000, 19.68, 4)


delete from HCategory
delete from VCategory
insert into HCategory( CategoryName)
values('ROSA DAMASCENA & Q10'),
('WHITE ROSE & OLIVE'),
('ROSA DAMASCENA & ARGAN')

insert into VCategory(CategoryName)
values('FACE SKIN CARE'),
('BODY CARE')