//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int CouponId { get; set; }
        public string UniqueId { get; set; }
        public int SiteUserId { get; set; }
        public System.DateTime Expires { get; set; }
        public Nullable<int> HCategoryId { get; set; }
        public Nullable<int> VCategoryId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public bool ForAll { get; set; }
        public int Discount { get; set; }
        public bool Used { get; set; }
        public byte[] Img { get; set; }
    
        public virtual HCategory HCategory { get; set; }
        public virtual Product Product { get; set; }
        public virtual SiteUser SiteUser { get; set; }
        public virtual VCategory VCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
