//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaristaEntities : DbContext
    {
        public MaristaEntities()
            : base("name=MaristaEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<SiteUser> SiteUsers { get; set; }
        public virtual DbSet<Constant> Constants { get; set; }
        public virtual DbSet<HCategory> HCategories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SOBonusSize> SOBonusSizes { get; set; }
        public virtual DbSet<VCategory> VCategories { get; set; }
        public virtual DbSet<BonusSize> BonusSizes { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<ChatItem> ChatItems { get; set; }
    }
}
