//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pyramid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pyramid()
        {
            this.Pyramid1 = new HashSet<Pyramid>();
            this.Pyramid11 = new HashSet<Pyramid>();
        }
    
        public int PyramidId { get; set; }
        public Nullable<int> PyramidParentId { get; set; }
        public Nullable<int> PyramidSpinoffParentId { get; set; }
        public int SiteUserId { get; set; }
        public decimal PBV { get; set; }
        public decimal Prcnt { get; set; }
        public decimal ParentPrcnt { get; set; }
        public decimal SoParentPrcnt { get; set; }
        public decimal SoPrcnt { get; set; }
        public decimal FromOthers { get; set; }
        public decimal ToReceive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pyramid> Pyramid1 { get; set; }
        public virtual Pyramid Pyramid2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pyramid> Pyramid11 { get; set; }
        public virtual Pyramid Pyramid3 { get; set; }
        public virtual SiteUser SiteUser { get; set; }
    }
}
