//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultHistory
    {
        public int ResultHistoryId { get; set; }
        public int BpId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> PBV { get; set; }
        public Nullable<decimal> NBV { get; set; }
        public Nullable<decimal> Bonus { get; set; }
    
        public virtual BP BP { get; set; }
    }
}
