//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUser
    {
        public int SiteUserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int LevelId { get; set; }
    
        public virtual Level Level { get; set; }
    }
}
