//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOBonusSize
    {
        public int SOBonusSizeId { get; set; }
        public int FromSO { get; set; }
        public int ToSO { get; set; }
        public decimal BonusPercent { get; set; }
    }
}
