//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v3MonthsBonuses
    {
        public int ResultHistoryId { get; set; }
        public string BPName { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public int SiteUserId { get; set; }
        public int ParentSiteId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
    }
}
