//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMyTeamReport
    {
        public int PyramidId { get; set; }
        public Nullable<int> PyramidParentId { get; set; }
        public int SiteUserId { get; set; }
        public Nullable<decimal> total { get; set; }
        public decimal ToReceive { get; set; }
        public decimal FromOthers { get; set; }
        public decimal PBV { get; set; }
        public string BPName { get; set; }
        public string EMail { get; set; }
    }
}
