//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marista.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalesTotal
    {
        public int SaleId { get; set; }
        public System.DateTime OnDate { get; set; }
        public Nullable<int> SiteUserId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
